### ISSUE TITLE
issue with main.py prepare

### ISSUE THREAD

**Issue by lancy-liang** [LuChenLab/SCAPE#12]
Traceback (most recent call last):
  File "/public/home/name/workspace/scRNA_APA/scape/SCAPE/main.py", line 4, in <module>
    cli()
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/public/home/name/workspace/scRNA_APA/scape/SCAPE/cli/prepare.py", line 177, in prepare
    intron_bed = intron_bed.subtract(exon_from_gtf, s=True)
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/public/home/name/miniconda3/envs/scape/lib/python3.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools subtract -s -b /tmp/pybedtools.y3ghahv1.tmp -a /tmp/pybedtools.novfpvyf.tmp

Error message was:
Error: unable to open file or unable to determine types for file /tmp/pybedtools.novfpvyf.tmp

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the 
  expected columns (e.g., cols 2 and 3 for BED).

(scape) [name@login1 script_me]$ cat prepare.sh 
#!/bin/bash
#SBATCH --job-name=main_py_prepare
#SBATCH --partition=big,low,amd
#SBATCH --nodes=1
#SBATCH --error=%j.err
#SBATCH --output=%j.out

python /public/home/name/workspace/scRNA_APA/scape/SCAPE/main.py prepare \
--gtf /public/home/name/workspace/gtf/species.109.chr.gtf.gz \
--prefix species

**Comment by lancy-liang** [comment]
.
