### ISSUE TITLE
ERROR when running prepare.py

### ISSUE THREAD

**Issue by Dongxu-Zheng** [LuChenLab/SCAPE#18]
Hi, thanks for developing this great software. I am working on a 10X single nucleus RNA-seq data. I use the gtf file from cellRanger as input for the prepare.py. However, I got the ERROR like this:

Traceback (most recent call last):
  File "/software/SCAPE/main.py", line 4, in <module>
    cli()
  File "/software/anaconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/software/anaconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/software/anaconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/software/anaconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/software/anaconda3/envs/scape/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/software/SCAPE/cli/prepare.py", line 83, in prepare
    if info[gene_type_id] not in genes_use:
TypeError: unhashable type: 'list'

I installed SCAPE according to the document. The version of Python is 3.7.3. Indeed, I have the output for UTR like:
1       30976   31097   lincRNA;ENSG00000243485;ENST00000473358;MIR1302-2HG     .       +
1       30976   31109   lincRNA;ENSG00000243485;ENST00000469289;MIR1302-2HG     .       +
1       34554   35174   lincRNA;ENSG00000237613;ENST00000417324;FAM138A .       -
1       35245   35481   lincRNA;ENSG00000237613;ENST00000461467;FAM138A .       -

I was wondering if I really need to care about the ERROR and if the output is correct? If you need more info. for my working environment, please let me know. Thanks for any reply and suggestions!

Cheers,
Dongxu

**Comment by zhou-ran** [comment]
Hi Dongxu,

Try the newest version of scape, https://github.com/chengl7-lab/scape 

Ran

**Comment by Dongxu-Zheng** [comment]
> Hi Dongxu,
> 
> Try the newest version of scape, https://github.com/chengl7-lab/scape
> 
> Ran

Hi Ran, thanks for your reply. I think there is some issues with installing scape visa pip. I got this ERROR:
ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python <3.11,>=3.9; 1.0.1 Requires-Python <3.11,>=3.9; 1.0.2 Requires-Python <3.11,>=3.9
ERROR: Could not find a version that satisfies the requirement scape-apa (from versions: none)
ERROR: No matching distribution found for scape-apa

But I can install it via git successfully and smoothly without any ERROR. I will run the pipeline on my data. Thanks!

Dongxu

**Comment by zhou-ran** [comment]
Hi Dongxu,

It appears that you've installed scape-apa using Python 3.8; however, the tool requires a minimum Python version of 3.9. Please consider upgrading your Python version accordingly.

You might consider initiating a new issue on that repository, where we can further discuss it.

Ran
